#include "gpk_enum.h"

#ifndef PCS_EFFECT_H_20934782908374
#define PCS_EFFECT_H_20934782908374
namespace pcs
{
	GDEFINE_ENUM_TYPE(COMBAT_STATUS, uint32_t);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, NONE				, 0x00000	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, BLIND				, 0x00001	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, STUN				, 0x00002	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, SHOCK				, 0x00004	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, BLEEDING			, 0x00008	);

	GDEFINE_ENUM_VALUE(COMBAT_STATUS, BURN				, 0x00010	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, POISON			, 0x00020	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, FREEZING			, 0x00040	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, PETRIFY			, 0x00080	);

	GDEFINE_ENUM_VALUE(COMBAT_STATUS, FROZEN			, 0x00100	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, BLACKOUT			, 0x00200	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, CHARMED			, 0x00400	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, DRUNK				, 0x00800	);

	GDEFINE_ENUM_VALUE(COMBAT_STATUS, SLEEP				, 0x01000	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, SLOW				, 0x02000	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, WEAKNESS			, 0x04000	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, PANIC				, 0x08000	);

	GDEFINE_ENUM_VALUE(COMBAT_STATUS, BERSERK			, 0x10000	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, INVISIBLE			, 0x20000	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, RAGE				, 0x40000	);
	GDEFINE_ENUM_VALUE(COMBAT_STATUS, BULLIED			, 0x80000	);
	
	GDEFINE_ENUM_TYPE(ATTACK_EFFECT, uint16_t);
	GDEFINE_ENUM_VALUE(ATTACK_EFFECT, NONE				, 0x00		);
	GDEFINE_ENUM_VALUE(ATTACK_EFFECT, LEECH_HEALTH		, 0x01		);
	GDEFINE_ENUM_VALUE(ATTACK_EFFECT, LEECH_MANA		, 0x02		);
	GDEFINE_ENUM_VALUE(ATTACK_EFFECT, LEECH_SHIELD		, 0x04		);
	GDEFINE_ENUM_VALUE(ATTACK_EFFECT, LEECH_ENERGY		, 0x08		);
	GDEFINE_ENUM_VALUE(ATTACK_EFFECT, LEECH_STAMINA		, 0x10		);
	GDEFINE_ENUM_VALUE(ATTACK_EFFECT, STEAL				, 0x20		);

	GDEFINE_ENUM_TYPE(DEFEND_EFFECT, uint16_t);
	GDEFINE_ENUM_VALUE(DEFEND_EFFECT, NONE				, 0x00		); 
	GDEFINE_ENUM_VALUE(DEFEND_EFFECT, REFLECT			, 0x01		); 	// Reflects damage to the attacker
	GDEFINE_ENUM_VALUE(DEFEND_EFFECT, BLIND				, 0x02		); 	// Blinds the attacker when inflicting 1 to 1 damage.
	GDEFINE_ENUM_VALUE(DEFEND_EFFECT, IMPENETRABLE		, 0x04		); 	// Reflects damage to the attacker
	GDEFINE_ENUM_VALUE(DEFEND_EFFECT, DEFLECT			, 0x08		); 	// Reflects damage to the attacker

	GDEFINE_ENUM_TYPE(PASSIVE_EFFECT, uint16_t);
	GDEFINE_ENUM_VALUE(PASSIVE_EFFECT, NONE				, 0x00		);
	GDEFINE_ENUM_VALUE(PASSIVE_EFFECT, REGEN_LIFE		, 0x01		);
	GDEFINE_ENUM_VALUE(PASSIVE_EFFECT, REGEN_MANA		, 0x02		);
	GDEFINE_ENUM_VALUE(PASSIVE_EFFECT, REGEN_ENERGY		, 0x04		);
	GDEFINE_ENUM_VALUE(PASSIVE_EFFECT, REGEN_STAMINA	, 0x04		);
	GDEFINE_ENUM_VALUE(PASSIVE_EFFECT, SHIELD_REPAIR	, 0x08		);
} // namespace

#endif // PCS_EFFECT_H_20934782908374